# 공통적용
#aws:
#  access-key: ${AWS_ACCESS_KEY:testKey}
#  secret-key: ${AWS_SECRET_KEY:secretKey}
#  s3:
#    bucket: ${AWS_S3_BUCKET:bucket}
#    private-bucket : ${AWS_S3_BUCKET_PRIVATE:bucket-private}
#    base-url: ${AWS_S3_BASE_URL:base-url}

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID:default}
    admin-key: ${KAKAO_ADMIN_KEY}
feign:
  kakao:
    info : https://kapi.kakao.com
    oauth : https://kauth.kakao.com
#ncp:
#  service-id: ${NCP_SERVICE_ID:}
#  access-key: ${NCP_ACCESS_KEY:}
#  secret-key: ${NCP_SECRET_KEY:}
#  plus-friend-id: ${NCP_PLUS_FRIEND_ID:}

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    com.depromeet.whatnow.api.* : debug

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.depromeet.whatnow.api.*: debug

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.depromeet.whatnow.api.*: debug
