# 공통적용
#aws:
#  access-key: ${AWS_ACCESS_KEY:testKey}
#  secret-key: ${AWS_SECRET_KEY:secretKey}
#  s3:
#    bucket: ${AWS_S3_BUCKET:bucket}
#    private-bucket : ${AWS_S3_BUCKET_PRIVATE:bucket-private}
#    base-url: ${AWS_S3_BASE_URL:base-url}
data:
  mongodb:
    url: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:cluster0.aybkvg3.mongodb.net}/${MONGO_DATABASE}?retryWrites=true&w=majority
    host: ${MONGO_HOST:cluster0.aybkvg3.mongodb.net}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

slack:
  webhook:
    token: ${SLACK_WEBHOOK_TOKEN:}
    url: ${SLACK_WEBHOOK_URL:}
    channel-id: ${SLACK_CHANNEL:}
    username: ${SLACK_USERNAME:default}
cache:
  caffeine:
    policy:
      maximum-size: 300
      expire-after-write: 300

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID:default}
    admin-key: ${KAKAO_ADMIN_KEY}

feign:
  kakao:
    info : https://kapi.kakao.com
    oauth : https://kauth.kakao.com

ncp:
  s3:
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    bucket: ${NCP_BUCKET}
    region: ${NCP_REGION}
    endpoint: ${NCP_ENDPOINT:https://kr.object.ncloudstorage.com}
  local:
    access-key: ${NCP_LOCAL_ACCESS_KEY}
    secret-key: ${NCP_LOCAL_SECRET_KEY}
    search-url: ${NCP_LOCAL_SEARCH_URL:https://openapi.naver.com/v1/search/local.json}


fcm:
  certification: ${FCM_CERTIFICATION:}
#ncp:
#  service-id: ${NCP_SERVICE_ID:}
#  access-key: ${NCP_ACCESS_KEY:}
#  secret-key: ${NCP_SECRET_KEY:}
#  plus-friend-id: ${NCP_PLUS_FRIEND_ID:}

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    com.depromeet.whatnow.api.* : debug
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.depromeet.whatnow.api.*: debug

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.depromeet.whatnow.api.*: debug
